import { format } from 'date-fns';

export const ReportFooter = () => {
  return (
    <div className="mt-12 pt-6 border-t border-gray-300">
      <div className="bg-blue-50 p-4 rounded-lg mb-4">
        <h4 className="font-semibold text-gray-900 mb-2 text-sm">Clinical Notes</h4>
        <div className="text-xs text-gray-700 space-y-1">
          <p>• This report is generated from parent-tracked data and should be used as supplementary information.</p>
          <p>• All timestamps are recorded in the parent's local timezone.</p>
          <p>• Please correlate this data with clinical observations and parental feedback.</p>
          <p>• Report any significant pattern changes or concerns to the healthcare provider.</p>
        </div>
      </div>
      
      <div className="flex justify-between items-center text-xs text-gray-500">
        <p>Generated by Baby Tracker App | {format(new Date(), 'MMM dd, yyyy HH:mm')}</p>
        <p>Page 1 of 1</p>
      </div>
      
      <p className="text-xs text-gray-400 text-center mt-4">
        This document contains confidential patient information. Please handle with appropriate care.
      </p>
    </div>
  );
};