// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjxxgccfazpkdfzbcgen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqeHhnY2NmYXpwa2RmemJjZ2VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDIyNDUsImV4cCI6MjA2NzMxODI0NX0.dfYtSo4xFI80fZjHUFE_p3a6J3QwkX90UiTzHc_Y7iQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});