// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfzjovujmhqxchnpyqtg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmempvdnVqbWhxeGNobnB5cXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDA0ODksImV4cCI6MjA2NDExNjQ4OX0.kZ8QAh9L9MRyANrKC6L24mOWaSNOojpIkwqVjtv7sOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);